[general]
# (required) The site name. Prepended to each generated output file.
sitename = "test"

[clean_list]
target_list_file_path = "input/target_list.txt"
exclude_list_file_path = "input/exclude_list.txt"

[xml_scan]
masscan_ip = "192.168.50.200"
interface = "eth0"
scan_rate = 3000
ports = [ "445", "443", "8443", "8080" ]
clean_target_list_file_path = "input/xml_clean_target_list.txt"

[web_scan]
clean_target_list_file_path = "input/web_clean_target_list.txt"
jitter = 0
ports = [ "80", "8000", "8080", "8443" ]
