name: Specter Project Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
  
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
 
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install tox
        pip install twine

    - name: Lint with yapf
      run: |
        tox -e lint

  publish:

    runs-on: ubuntu-latest

    needs: validate
  
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}

    steps:

    - uses: actions/checkout@v2
  
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
 
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install tox
        pip install twine

    - name: Build package
      run: |
        tox -e package-build

    - name: Check package build
      run: |
        tox -e package-check

    - name: Upload package to test.pypi
      run: |
        tox -e package-test-upload
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

    - name: Upload package to pypi
      run: |
        tox -e package-upload
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
